# Generated by Django 3.0.7 on 2020-06-08 08:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200608_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None),
        ),
    ]
